### ISSUE TITLE
Type error: Property 'recurringInterval' does not exist on type 'ProductPriceOutput' - but does compile and work

### ISSUE THREAD

**Issue by xn1cklas** [polarsource/polar-js#7]
In [ProductListResponse](https://github.com/polarsource/polar-js/blob/main/docs/models/operations/productslistresponse.md) holds an object called result with an array of items of type [ProductOutput](https://github.com/polarsource/polar-js/blob/67464198b04b832cc1efa71d0e17e85e2aa98039/src/models/components/productoutput.ts#L42). 

Within each item is the prices array which holds items of type ProductPriceOutput.

It does work perfectly fine, though it throws this TypeScript error:

`Property 'recurringInterval' does not exist on type 'ProductPriceOutput'.
  Property 'recurringInterval' does not exist on type 'ProductPriceOneTime & { type: "one_time"; }'.ts(2339)`

**Comment by frankie567** [comment]
Yes, that's totally expected. `ProductPriceOutput` is a union consisting of `ProductPriceOneTime` (for one-time products) and `ProductPriceRecurring` (for subscriptions).

https://github.com/polarsource/polar-js/blob/67464198b04b832cc1efa71d0e17e85e2aa98039/src/models/components/productpriceoutput.ts#L19-21

Only `ProductPriceRecurring` has the `recurringInterval` property, hence the TS error.

If you had a check on `type`, TS should be able to infer the correct type:

```ts
if (price.type === 'recurring') {
    console.log(price.recurringInterval)
}
```

**Comment by xn1cklas** [comment]
This makes total sense! Thanks, got it working now!
